module NPFSApp
{
  typedef sequence<string> files;
  typedef sequence<string> servers;
  
  interface FileServer
  {
    boolean openFile(in string filename);
    oneway void closeFile();
    files getFiles();
    oneway void modifyFile();
    boolean hasFile(in string filename);
    string getIpAddress();
    boolean testResponse();
    servers getConnectedServers();
    oneway void addServer(in FileServer server);
  };
};
