module NPFSApp
{
  typedef sequence<string> files;
  interface FileServer
  {
    boolean openFile(in string filename);
    oneway void closeFile();
    files getFiles();
    oneway void modifyFile();
    boolean hasFile(in string filename);
  };
};
