package NPFSApp;


/**
* NPFSApp/dataBufferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Wednesday, December 10, 2014 11:09:25 PM EST
*/

public final class dataBufferHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public dataBufferHolder ()
  {
  }

  public dataBufferHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NPFSApp.dataBufferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NPFSApp.dataBufferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NPFSApp.dataBufferHelper.type ();
  }

}
