package NPFSApp;


/**
* NPFSApp/FileServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Thursday, December 4, 2014 11:37:01 AM EST
*/

public interface FileServer extends FileServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileServer
