package NPFSApp;


/**
* NPFSApp/FileServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Wednesday, December 10, 2014 11:09:25 PM EST
*/

public interface FileServerOperations 
{
  boolean getFile (String filename);
  String openFile (String filename, long start, long end, int sessionID);
  long getFileSize (String filename);
  boolean closeFile (byte[] data, int sessionID);
  String[] getAllFiles ();
  String[] myFiles ();
  boolean hasFile (String filename);
  String getIpAddress ();
  boolean testResponse ();
  String[] getConnectedServers ();
  void addServer (NPFSApp.FileServer server);
  int getSessionID ();
  boolean checkVersion (String filename, int version);
  int getVersion (String filename);
  void purgeFile (String filename);
} // interface FileServerOperations
