package NPFSApp;


/**
* NPFSApp/FileServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Wednesday, December 10, 2014 11:09:25 PM EST
*/

public abstract class FileServerPOA extends org.omg.PortableServer.Servant
 implements NPFSApp.FileServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getFile", new java.lang.Integer (0));
    _methods.put ("openFile", new java.lang.Integer (1));
    _methods.put ("getFileSize", new java.lang.Integer (2));
    _methods.put ("closeFile", new java.lang.Integer (3));
    _methods.put ("getAllFiles", new java.lang.Integer (4));
    _methods.put ("myFiles", new java.lang.Integer (5));
    _methods.put ("hasFile", new java.lang.Integer (6));
    _methods.put ("getIpAddress", new java.lang.Integer (7));
    _methods.put ("testResponse", new java.lang.Integer (8));
    _methods.put ("getConnectedServers", new java.lang.Integer (9));
    _methods.put ("addServer", new java.lang.Integer (10));
    _methods.put ("getSessionID", new java.lang.Integer (11));
    _methods.put ("checkVersion", new java.lang.Integer (12));
    _methods.put ("getVersion", new java.lang.Integer (13));
    _methods.put ("purgeFile", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // NPFSApp/FileServer/getFile
       {
         String filename = in.read_string ();
         boolean $result = false;
         $result = this.getFile (filename);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // NPFSApp/FileServer/openFile
       {
         String filename = in.read_string ();
         long start = in.read_longlong ();
         long end = in.read_longlong ();
         int sessionID = in.read_long ();
         String $result = null;
         $result = this.openFile (filename, start, end, sessionID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // NPFSApp/FileServer/getFileSize
       {
         String filename = in.read_string ();
         long $result = (long)0;
         $result = this.getFileSize (filename);
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 3:  // NPFSApp/FileServer/closeFile
       {
         byte data[] = NPFSApp.dataBufferHelper.read (in);
         int sessionID = in.read_long ();
         boolean $result = false;
         $result = this.closeFile (data, sessionID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // NPFSApp/FileServer/getAllFiles
       {
         String $result[] = null;
         $result = this.getAllFiles ();
         out = $rh.createReply();
         NPFSApp.filesHelper.write (out, $result);
         break;
       }

       case 5:  // NPFSApp/FileServer/myFiles
       {
         String $result[] = null;
         $result = this.myFiles ();
         out = $rh.createReply();
         NPFSApp.filesHelper.write (out, $result);
         break;
       }

       case 6:  // NPFSApp/FileServer/hasFile
       {
         String filename = in.read_string ();
         boolean $result = false;
         $result = this.hasFile (filename);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // NPFSApp/FileServer/getIpAddress
       {
         String $result = null;
         $result = this.getIpAddress ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // NPFSApp/FileServer/testResponse
       {
         boolean $result = false;
         $result = this.testResponse ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // NPFSApp/FileServer/getConnectedServers
       {
         String $result[] = null;
         $result = this.getConnectedServers ();
         out = $rh.createReply();
         NPFSApp.serversHelper.write (out, $result);
         break;
       }

       case 10:  // NPFSApp/FileServer/addServer
       {
         NPFSApp.FileServer server = NPFSApp.FileServerHelper.read (in);
         this.addServer (server);
         out = $rh.createReply();
         break;
       }

       case 11:  // NPFSApp/FileServer/getSessionID
       {
         int $result = (int)0;
         $result = this.getSessionID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 12:  // NPFSApp/FileServer/checkVersion
       {
         String filename = in.read_string ();
         int version = in.read_long ();
         boolean $result = false;
         $result = this.checkVersion (filename, version);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 13:  // NPFSApp/FileServer/getVersion
       {
         String filename = in.read_string ();
         int $result = (int)0;
         $result = this.getVersion (filename);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 14:  // NPFSApp/FileServer/purgeFile
       {
         String filename = in.read_string ();
         this.purgeFile (filename);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NPFSApp/FileServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileServer _this() 
  {
    return FileServerHelper.narrow(
    super._this_object());
  }

  public FileServer _this(org.omg.CORBA.ORB orb) 
  {
    return FileServerHelper.narrow(
    super._this_object(orb));
  }


} // class FileServerPOA
