package NPFSApp;


/**
* NPFSApp/FileServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Thursday, December 4, 2014 11:37:01 AM EST
*/

public interface FileServerOperations 
{
  boolean openFile (String filename);
  void closeFile ();
  String[] getFiles ();
  void modifyFile ();
  boolean hasFile (String filename);
  String getIpAddress ();
  boolean testResponse ();
} // interface FileServerOperations
