package NPFSApp;


/**
* NPFSApp/filesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Wednesday, December 10, 2014 11:09:25 PM EST
*/

public final class filesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public filesHolder ()
  {
  }

  public filesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NPFSApp.filesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NPFSApp.filesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NPFSApp.filesHelper.type ();
  }

}
