package NPFSApp;


/**
* NPFSApp/FileServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Thursday, December 4, 2014 12:05:45 PM EST
*/

public abstract class FileServerPOA extends org.omg.PortableServer.Servant
 implements NPFSApp.FileServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer> ();
  static
  {
    _methods.put ("openFile", new java.lang.Integer (0));
    _methods.put ("closeFile", new java.lang.Integer (1));
    _methods.put ("getFiles", new java.lang.Integer (2));
    _methods.put ("modifyFile", new java.lang.Integer (3));
    _methods.put ("hasFile", new java.lang.Integer (4));
    _methods.put ("getIpAddress", new java.lang.Integer (5));
    _methods.put ("testResponse", new java.lang.Integer (6));
    _methods.put ("getConnectedServers", new java.lang.Integer (7));
    _methods.put ("addServer", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // NPFSApp/FileServer/openFile
       {
         String filename = in.read_string ();
         boolean $result = false;
         $result = this.openFile (filename);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // NPFSApp/FileServer/closeFile
       {
         this.closeFile ();
         out = $rh.createReply();
         break;
       }

       case 2:  // NPFSApp/FileServer/getFiles
       {
         String $result[] = null;
         $result = this.getFiles ();
         out = $rh.createReply();
         NPFSApp.filesHelper.write (out, $result);
         break;
       }

       case 3:  // NPFSApp/FileServer/modifyFile
       {
         this.modifyFile ();
         out = $rh.createReply();
         break;
       }

       case 4:  // NPFSApp/FileServer/hasFile
       {
         String filename = in.read_string ();
         boolean $result = false;
         $result = this.hasFile (filename);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // NPFSApp/FileServer/getIpAddress
       {
         String $result = null;
         $result = this.getIpAddress ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // NPFSApp/FileServer/testResponse
       {
         boolean $result = false;
         $result = this.testResponse ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // NPFSApp/FileServer/getConnectedServers
       {
         String $result[] = null;
         $result = this.getConnectedServers ();
         out = $rh.createReply();
         NPFSApp.serversHelper.write (out, $result);
         break;
       }

       case 8:  // NPFSApp/FileServer/addServer
       {
         NPFSApp.FileServer server = NPFSApp.FileServerHelper.read (in);
         this.addServer (server);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NPFSApp/FileServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileServer _this() 
  {
    return FileServerHelper.narrow(
    super._this_object());
  }

  public FileServer _this(org.omg.CORBA.ORB orb) 
  {
    return FileServerHelper.narrow(
    super._this_object(orb));
  }


} // class FileServerPOA
