package NPFSApp;


/**
* NPFSApp/FileServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Thursday, December 4, 2014 12:05:45 PM EST
*/

abstract public class FileServerHelper
{
  private static String  _id = "IDL:NPFSApp/FileServer:1.0";

  public static void insert (org.omg.CORBA.Any a, NPFSApp.FileServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NPFSApp.FileServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NPFSApp.FileServerHelper.id (), "FileServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NPFSApp.FileServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NPFSApp.FileServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NPFSApp.FileServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NPFSApp.FileServer)
      return (NPFSApp.FileServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NPFSApp._FileServerStub stub = new NPFSApp._FileServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NPFSApp.FileServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NPFSApp.FileServer)
      return (NPFSApp.FileServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NPFSApp._FileServerStub stub = new NPFSApp._FileServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
