package NPFSApp;


/**
* NPFSApp/serversHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from npfs.idl
* Thursday, December 11, 2014 11:04:05 AM EST
*/

public final class serversHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public serversHolder ()
  {
  }

  public serversHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NPFSApp.serversHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NPFSApp.serversHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NPFSApp.serversHelper.type ();
  }

}
